platform :ios, "9.0"

target "trackplayerSwift" do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for trackplayerSwift
  pod "Fabric"
  pod "Crashlytics"

  rn_path = "../node_modules/react-native"
  pod "yoga", path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod "React", path: rn_path, subspecs: [
             "Core",
             "CxxBridge", # Include this for RN >= 0.47
             "DevSupport", # Include this to enable In-App Devmenu if RN >= 0.43
             "RCTText",
             "RCTNetwork",
             "RCTWebSocket", # Needed for debugging
             "RCTAnimation",
             "RCTActionSheet",
             "RCTGeolocation",
             "RCTImage",
             "RCTLinkingIOS",
             "RCTSettings",
             "RCTVibration",
           ]

  pod "DoubleConversion", :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod "glog", :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec"
  pod "Folly", :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  pod "react-native-video/VideoCaching", :path => "../node_modules/react-native-video/react-native-video.podspec"

  pod "google-cast-sdk", "~> 3"

  pod 'react-native-music-control', :path => '../node_modules/react-native-music-control'


  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"

      targets_to_ignore = %w(React yoga)

      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end
end
